services:
  - type: web
    name: sentinel-sat
    env: python
    plan: free
    buildCommand: python main.py
    startCommand: python main.py
    healthCheckPath: /api/health
    autoDeploy: yes
    envVars:
      - key: HF_TOKEN
        sync: false
      - key: ESP_STREAM_URL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
